-- 코드를 입력하세요
SELECT 
    C.CAR_ID 
    , C.CAR_TYPE 
    , ROUND(SUM(C.DAILY_FEE * 30 * TO_CHAR((100 - D.DISCOUNT_RATE) / 100, 'FM9990.999')), 0) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR C 
JOIN (
    SELECT 
        CAR_ID 
        , MAX(END_DATE) AS ED 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    GROUP BY CAR_ID
) H 
ON C.CAR_ID = H.CAR_ID 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D 
ON C.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = '30일 이상' 
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV') 
AND TO_CHAR(H.ED, 'YYYY-MM-DD') < '2022-11-01' 
AND C.DAILY_FEE * 30 * TO_CHAR((100 - D.DISCOUNT_RATE) / 100, 'FM9990.999') >= 500000 
AND C.DAILY_FEE * 30 * TO_CHAR((100 - D.DISCOUNT_RATE) / 100, 'FM9990.999') < 2000000 
GROUP BY C.CAR_ID, C.CAR_TYPE 
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;