-- 코드를 입력하세요
SELECT 
    A.ANIMAL_ID 
    , A.NAME 
FROM(
    SELECT 
        I.ANIMAL_ID 
        , I.NAME 
        , ROW_NUMBER() OVER(ORDER BY O.DATETIME - I.DATETIME + 1 DESC) AS RANK 
    FROM ANIMAL_INS I 
    JOIN ANIMAL_OUTS O 
    ON I.ANIMAL_ID = O.ANIMAL_ID 
    ORDER BY O.DATETIME - I.DATETIME + 1 DESC 
) A 
WHERE A.RANK <= 2;