-- 코드를 입력하세요
SELECT 
    TO_NUMBER(TO_CHAR(S.SALES_DATE, 'YYYY')) AS YEAR 
    , TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) AS MONTH 
    , COUNT(DISTINCT(S.USER_ID)) AS PUCHASED_USERS 
    , ROUND((COUNT(DISTINCT(S.USER_ID))) / 
                    (SELECT COUNT(USER_ID) 
                       FROM USER_INFO 
                      WHERE TO_CHAR(JOINED, 'YYYY') = '2021'), 1)
                         AS PUCHASED_RATIO 
FROM (
    SELECT 
        O.USER_ID 
        , O.SALES_DATE 
    FROM ONLINE_SALE O 
    JOIN USER_INFO U 
    ON O.USER_ID = U.USER_ID 
    WHERE TO_CHAR(U.JOINED, 'YYYY') = '2021' 
) S 
GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) 
ORDER BY YEAR, MONTH;