-- 코드를 입력하세요
SELECT 
    TO_NUMBER(LTRIM(TO_CHAR(START_DATE, 'MM'), 0)) AS MONTH 
    , CAR_ID 
    , COUNT(HISTORY_ID) AS RECORDS 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN 
(
    SELECT 
        CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10' 
    GROUP BY CAR_ID 
    HAVING COUNT(HISTORY_ID) >= 5 
) AND TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10' 
GROUP BY TO_NUMBER(LTRIM(TO_CHAR(START_DATE, 'MM'), 0)), CAR_ID 
HAVING COUNT(HISTORY_ID) != 0 
ORDER BY MONTH, CAR_ID DESC;