-- 코드를 입력하세요
SELECT 
    A.FLAVOR 
FROM ( 
    SELECT 
        F.FLAVOR 
        , ROW_NUMBER() OVER (ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC) 
            AS RANK 
    FROM FIRST_HALF F 
    RIGHT JOIN JULY J 
    ON F.FLAVOR = J.FLAVOR 
    GROUP BY F.FLAVOR 
) A 
WHERE A.RANK <= 3 
ORDER BY A.RANK;