-- 코드를 입력하세요
SELECT 
    A.NAME 
    , A.DATETIME 
FROM (
    SELECT 
        I.ANIMAL_ID 
        , I.NAME 
        , I.DATETIME 
        , ROW_NUMBER() OVER(ORDER BY I.DATETIME) AS RANK 
    FROM ANIMAL_INS I 
    LEFT JOIN ANIMAL_OUTS O 
    ON I.ANIMAL_ID = O.ANIMAL_ID 
    WHERE O.ANIMAL_ID IS NULL
) A 
WHERE A.RANK <= 3 
ORDER BY A.DATETIME;