-- 코드를 입력하세요
-- SELECT 
--     T.AUTHOR_ID 
--     , A.AUTHOR_NAME 
--     , T.CATEGORY 
--     , S.SALES 
-- FROM (
--     SELECT 
--         B.AUTHOR_ID 
--         A.AUTHOR_NAME 
--         , B.CATEGORY 
--         , SUM(S.SALES * B.PRICE) AS TOTAL_SALES 
--     FROM BOOK B 
--     JOIN BOOK_SALES S 
--     ON B.BOOK_ID = S.BOOK_ID 
--     JOIN AUTHOR A 
--     ON B.AUTHOR_ID = A.AUTHOR_ID 
--     GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY 
-- ) T 
-- -- JOIN BOOK B 
-- -- ON T.AUTHOR_ID = B.AUTHOR_ID 
-- -- JOIN BOOK_SALES S 
-- -- ON B.BOOK_ID = S.BOOK_ID 
-- -- JOIN AUTHOR A 
-- -- ON B.AUTHOR_ID = A.AUTHOR_ID 
-- WHERE TO_CHAR(S.SALES_DATE, 'YYYY-MM') = '2022-01' 
-- ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;

-- SELECT 
--         B.AUTHOR_ID 
--         , A.AUTHOR_NAME 
--         , B.CATEGORY 
--         , SUM(S.SALES * B.PRICE) AS TOTAL_SALES 
--     FROM BOOK B 
--     JOIN BOOK_SALES S 
--     ON B.BOOK_ID = S.BOOK_ID 
--     JOIN AUTHOR A 
--     ON B.AUTHOR_ID = A.AUTHOR_ID 
--     GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY;

 SELECT 
        DISTINCT(A.AUTHOR_ID) 
        , A.AUTHOR_NAME 
        , B.CATEGORY 
        , SUM(S.SALES * B.PRICE) OVER 
            (PARTITION BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY)AS TOTAL_SALES 
    FROM BOOK B 
    JOIN AUTHOR A 
    ON B.AUTHOR_ID = A.AUTHOR_ID 
    JOIN BOOK_SALES S 
    ON B.BOOK_ID = S.BOOK_ID 
WHERE TO_CHAR(S.SALES_DATE, 'YYYY-MM') = '2022-01' 
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;