-- 코드를 입력하세요
SELECT 
    H.HISTORY_ID 
    , ROUND(SUM(CASE WHEN H.DIFF < 7 THEN C.DAILY_FEE * H.DIFF 
        WHEN H.DIFF >= 7 THEN C.DAILY_FEE * H.DIFF * TO_CHAR((100 - D.DISCOUNT_RATE) / 100, 'FM9990.999') END), 0) AS FEE 
FROM (
    SELECT 
        HISTORY_ID 
        , CAR_ID 
        , (END_DATE - START_DATE) + 1 AS DIFF 
        , CASE WHEN (END_DATE - START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상' 
            WHEN (END_DATE - START_DATE) + 1 BETWEEN 30 AND 89 THEN '30일 이상' 
            WHEN (END_DATE - START_DATE) + 1 >= 90 THEN '90일 이상' 
            ELSE NULL 
            END AS DURATION 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
) H 
JOIN CAR_RENTAL_COMPANY_CAR C 
ON H.CAR_ID = C.CAR_ID 
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D 
ON C.CAR_TYPE = D.CAR_TYPE AND H.DURATION = D.DURATION_TYPE 
WHERE C.CAR_TYPE = '트럭' 
GROUP BY H.HISTORY_ID 
ORDER BY FEE DESC, H.HISTORY_ID DESC;